# Generated by Django 5.2 on 2025-04-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('commission_eligible', models.BooleanField(default=False)),
                ('commission_type', models.CharField(choices=[('Percentage', 'Percentage'), ('Fixed Rate', 'Fixed Rate'), ('No Commission', 'No Commission')], max_length=50)),
                ('commission_rate', models.PositiveIntegerField()),
            ],
        ),
    ]
