# Generated by Django 5.2 on 2025-04-21 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_company_peme_rate'),
        ('setpackages', '0001_initial'),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Package',
            new_name='Setpackage',
        ),
        migrations.RenameModel(
            old_name='PackageTest',
            new_name='SetpackageTest',
        ),
        migrations.RenameField(
            model_name='setpackage',
            old_name='name',
            new_name='package_name',
        ),
        migrations.RenameField(
            model_name='setpackage',
            old_name='promo_price',
            new_name='package_promo_price',
        ),
        migrations.RenameField(
            model_name='setpackage',
            old_name='transaction_purpose',
            new_name='package_transaction_purpose',
        ),
    ]
