# Generated by Django 5.2 on 2025-04-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_company_peme_rate'),
        ('setpackages', '0002_rename_package_setpackage_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='setpackage',
            constraint=models.UniqueConstraint(fields=('company', 'package_name', 'package_transaction_purpose'), name='unique_package_per_company'),
        ),
    ]
