# Generated by Django 5.2 on 2025-04-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=50)),
                ('test_price', models.PositiveIntegerField()),
                ('test_package_exclusion_rate', models.PositiveIntegerField()),
                ('test_category', models.CharField(choices=[('Hematology', 'Hematology'), ('Clinical Microscopy', 'Clinical Microscopy'), ('Pregnancy Test', 'Pregnancy Test'), ('Blood Chemistry', 'Blood Chemistry'), ('Liver Function', 'Liver Function'), ('Electrolytes', 'Electrolytes'), ('Tumor Markers', 'Tumor Markers'), ('Serology', 'Serology'), ('Immunology', 'Immunology'), ('Hormone', 'Hormone'), ('Hepatitis', 'Hepatitis'), ('Xray', 'Xray'), ('Ultrasound', 'Ultrasound'), ('Xray', 'Xray'), ('Others', 'Others')], max_length=50)),
            ],
        ),
    ]
