# Generated by Django 5.2 on 2025-04-09 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('contact_no', models.CharField(max_length=11)),
                ('age', models.PositiveIntegerField()),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Charged', 'Charged')], max_length=25)),
                ('transaction_type', models.CharField(choices=[('Company', 'Company'), ('Walk-in', 'Walk-in')], max_length=25)),
                ('company_id', models.PositiveIntegerField()),
                ('transaction_purpose', models.CharField(choices=[('Pre-Employment Examination (PEME)', 'Pre-Employment Examination (PEME)'), ('Annual Physical Examination (APE)', 'Annual Physical Examination (APE)'), ('Other Test', 'Other Test')], max_length=50)),
                ('has_drug_test', models.BooleanField(default=False)),
                ('custody_control_form_submitted', models.BooleanField(default=False)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('transaction_time', models.DateField(auto_now_add=True)),
                ('tests', models.CharField(max_length=256)),
                ('transaction_status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='patients.patient')),
            ],
        ),
    ]
