# Generated by Django 5.2 on 2025-04-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_transaction_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='discount_rate',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='discount_type',
            field=models.CharField(choices=[('Philhealth', 'Philhealth'), ('Senior Citizen', 'Senior Citizen')], default='NO_DISCOUNT', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='discounted_total',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_discounted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_total',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
