# Generated by Django 5.2 on 2025-04-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_discount_rate_transaction_discount_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='discount_type',
            field=models.CharField(choices=[('Philhealth', 'Philhealth'), ('Senior Citizen', 'Senior Citizen'), ('Package Exclusion', 'Package Exclusion')], max_length=25),
        ),
    ]
