# Generated by Django 5.2 on 2025-04-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
        ('transactions', '0004_alter_transaction_discount_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_discounted',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='discount_rate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='discount_type',
            field=models.CharField(choices=[('Philhealth', 'Philhealth'), ('Senior Citizen', 'Senior Citizen'), ('PWD', 'PWD'), ('Package Exclusion', 'Package Exclusion'), ('No Discount', 'No Discount')], default='No Discount', max_length=25),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='discounted_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tests',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tests',
            field=models.ManyToManyField(related_name='transactions', to='tests.test'),
        ),
    ]
