# Generated by Django 5.2 on 2025-04-15 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
        ('transactions', '0005_remove_transaction_is_discounted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='tests',
        ),
        migrations.CreateModel(
            name='TransactionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_price', models.PositiveIntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_transactions', to='tests.test')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_tests', to='transactions.transaction')),
            ],
        ),
    ]
