# Generated by Django 5.2 on 2025-04-15 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('transactions', '0006_remove_transaction_tests_transactiontest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='company_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='companies.company'),
            preserve_default=False,
        ),
    ]
