# Generated by Django 5.2 on 2025-04-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_remove_transaction_company_id_transaction_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Ongoing', 'Ongoing'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], max_length=50),
        ),
    ]
