# Generated by Django 5.2 on 2025-04-22 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setpackages', '0002_rename_package_setpackage_and_more'),
        ('transactions', '0008_alter_transaction_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='setpackage',
            field=models.ForeignKey(blank=True, help_text='The company/package combo selected for this transaction, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='setpackages.setpackage'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_purpose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
