# Generated by Django 5.2 on 2025-04-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_transaction_setpackage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_philhealth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_philhealth_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_pwd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_senior_citizen',
            field=models.BooleanField(default=False),
        ),
    ]
