# Generated by Django 4.2.20 on 2025-05-04 23:05

from django.db import migrations, models
import transactions.models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_transaction_is_philhealth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(default=transactions.models.get_manila_date, help_text='Date based on Asia/Manila'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_time',
            field=models.TimeField(default=transactions.models.get_manila_time, help_text='Time based on Asia/Manila'),
        ),
    ]
